name:                euler
version:             0.1.0.0
github:              "pechersky/hs-euler"
license:             BSD3
author:              "Yakov Pechersky"
maintainer:          "yakov@pechersky.us"
copyright:           "2017 Yakov Pechersky"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/pechersky/hs-euler#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options: -Wall -fno-warn-unused-top-binds
  default-extensions:
    - NumDecimals
    - TypeApplications
    - ViewPatterns
    - TupleSections
  dependencies:
    - primes
    - containers
    - vector
    - linear
    - text
    - numerals
    - time
    - split
    - digits
    - megaparsec
    - transformers
    - lens
    - control-monad-omega
    - data-ordlist

executables:
  euler-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - euler
    - template-haskell

tests:
  euler-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - euler
